"""
Django settings for CalTutors project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os
import stripe

print(">>> LOADING DJANGO SETTINGS from", os.getcwd())
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent 
# Environment setup
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / ".env")

# Core settings
DEBUG = env("DEBUG", default=False)
LOG_LEVEL = env("LOG_LEVEL", default="INFO").upper()

# Ensure logs/ exists
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")


# ALLOWED_HOSTS configuration
raw_allowed_hosts = env("DJANGO_ALLOWED_HOSTS", default="localhost,127.0.0.1")
ALLOWED_HOSTS = [h.strip() for h in raw_allowed_hosts.split(",") if h.strip()]

# CORS configuration
raw_cors_origins = env("CORS_ALLOWED_ORIGINS", default="")
if raw_cors_origins:
    CORS_ALLOWED_ORIGINS = [
        origin.strip() for origin in raw_cors_origins.split(",") if origin.strip()
    ]
else:
    CORS_ALLOWED_ORIGINS = []

# Add localhost for development
if DEBUG:
    CORS_ALLOWED_ORIGINS.extend(
        [
            "http://localhost:3000",
            "http://127.0.0.1:3000",
        ]
    )

# Security settings for production
if not DEBUG:
    # HTTPS settings
    SECURE_SSL_REDIRECT = env("SECURE_SSL_REDIRECT", default=True, cast=bool)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # General security settings
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
else:
    # Development settings - less restrictive
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False

# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "apps.accounts",
    "apps.sessions",
    "apps.payments",
    "apps.admin_management",
    # third-party
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # 'django.middleware.csrf.CsrfViewMiddleware',  # Not needed for token-based API
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "CalTutors.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, 'apps', 'emails', 'templates')
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "CalTutors.wsgi.application"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ]
    if not DEBUG
    else [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {"anon": "100/hour", "user": "1000/hour"}
    if not DEBUG
    else {"anon": "1000/hour", "user": "10000/hour"},
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": env.db(  # parses DATABASE_URL
        default="postgresql://postgres:postgres@127.0.0.1:5432/postgres"
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = "accounts.User"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Media files (for user uploads if needed in the future)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# LOGGING
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs/debug.log"),
            "formatter": "verbose",
        },
    },
    "loggers": {
        "root": {
            "handlers": ["console", "file"],
            "level": "INFO" if DEBUG else "WARNING",
        },
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO" if DEBUG else "WARNING",
            "propagate": False,
        },
        "stripe": {
            "handlers": ["console", "file"],
            "level": "WARNING",
            "propagate": False,
        },
        "postmarker": {
            "handlers": ["console", "file"],
            "level": "WARNING",
            "propagate": False,
        },
        "urllib3": {
            "handlers": ["console", "file"],
            "level": "WARNING",
            "propagate": False,
        },
        "httpx": {
            "handlers": ["console", "file"],
            "level": "WARNING",
            "propagate": False,
        },

        # Silence font tools
        "fontTools": {
            "handlers": ["console", "file"],
            "level": "WARNING",
            "propagate": False,
        },
        "fontTools.subset": {
            "handlers": ["console", "file"],
            "level": "ERROR",   
            "propagate": False,
        },
        "fontTools.ttLib": {
            "handlers": ["console", "file"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

# Stripe Configuration
STRIPE_PUBLISHABLE_KEY = env("STRIPE_PUBLISHABLE_KEY", default="")
STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY", default="")
stripe.api_key = STRIPE_SECRET_KEY
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET", default="")

# Frontend URL for redirects
FRONTEND_URL = env("FRONTEND_URL", default="http://localhost:3000")

# Email Configuration
EMAIL_BACKEND = env("EMAIL_BACKEND", default="")
if EMAIL_BACKEND == "POSTMARK":
    EMAIL_BACKEND = "postmarker.django.EmailBackend"
    POSTMARK_DEFAULT_SENDER = env("POSTMARK_DEFAULT_SENDER", default="info@caltutors.org")
    POSTMARK = {
        'TOKEN': env("POSTMARK_API_TOKEN"),
        'TEST_MODE': False,
        'VERBOSITY': 0,
    }
else:
    print(" WARNING: Email backend not specified, using default")
    # Dev: print emails to console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Consistent sender defaults
DEFAULT_FROM_EMAIL = os.getenv("POSTMARK_DEFAULT_SENDER", "info@caltutors.org")
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Password Reset Configuration
PASSWORD_RESET_TIMEOUT = 3600  # 1 hour in seconds

# Session Configuration
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

# Note: CSRF protection disabled for token-based API

# Cache Configuration (optional - for production performance)
if not DEBUG:
    CACHES = (
        {
            "default": {
                "BACKEND": "django.core.cache.backends.redis.RedisCache",
                "LOCATION": env("REDIS_URL", default="redis://127.0.0.1:6379/1"),
            }
        }
        if env("REDIS_URL", default=None)
        else {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            }
        }
    )

# Celery / Redis
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default=CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "run-go-charger-weekly": {
        "task": "apps.payments.tasks.run_go_charger",
        "schedule": crontab(hour=6, minute=0, day_of_week="mon"),
    },
}

print("🟩 LOADED CELERY_BEAT_SCHEDULE:", CELERY_BEAT_SCHEDULE)
