# Generated by Django 5.2.5 on 2025-08-31 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate in dollars that the student pays', max_digits=8)),
                ('tutor_pay_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate in dollars that the tutor gets paid', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_rates', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(limit_choices_to={'user_type': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutoring Rate',
                'verbose_name_plural': 'Tutoring Rates',
                'ordering': ['tutor__first_name', 'student__first_name'],
                'unique_together': {('tutor', 'student')},
            },
        ),
    ]
