# Generated by Django 5.2.5 on 2025-09-03 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring_sessions", "0002_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Charge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total hours (calculated from session durations)",
                        max_digits=6,
                    ),
                ),
                (
                    "student_charge_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount to charge the student",
                        max_digits=10,
                    ),
                ),
                (
                    "tutor_payment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount to pay the tutor",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Payment"),
                            ("paid_by_student", "Paid by Student"),
                            ("paid_to_tutor", "Paid to Tutor"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("charge_period_start", models.DateField()),
                ("charge_period_end", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("charged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges",
                        to="tutoring_sessions.rate",
                    ),
                ),
                (
                    "sessions",
                    models.ManyToManyField(
                        help_text="Sessions included in this charge",
                        related_name="charges",
                        to="tutoring_sessions.hours",
                    ),
                ),
            ],
            options={
                "verbose_name": "Charge",
                "verbose_name_plural": "Charges",
                "ordering": ["-created_at"],
            },
        ),
    ]
