# Generated by Django 5.2.5 on 2025-09-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring_sessions", "0003_charge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charge",
            name="student_charge_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total amount to charge the student",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="total_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total hours (calculated from session durations)",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="tutor_payment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total amount to pay the tutor",
                max_digits=10,
            ),
        ),
    ]
