# Generated by Django 5.2.5 on 2025-09-05 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_sessions', '0004_alter_charge_student_charge_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hours',
            table='tutoring_sessions',
        ),
    ]
