# Generated by Django 5.2.5 on 2025-09-07 04:41

from django.db import migrations


def migrate_students_to_new_model(apps, schema_editor):
    """
    Create Student records for existing Users with 'student' type.
    No existing Hours or Rate records to migrate since they were cleared.
    """
    User = apps.get_model('accounts', 'User')
    Student = apps.get_model('accounts', 'Student')
    
    # Get all users with 'student' type (before we changed it to 'client')
    student_users = User.objects.filter(user_type='student')
    
    for user in student_users:
        # Change user type to 'client'
        user.user_type = 'client'
        user.save()
        
        # Create corresponding Student record
        Student.objects.create(
            client=user,
            first_name=user.first_name,
            last_name=user.last_name,
            email=user.email,
            phone_number=user.phone_number,
            is_active=True
        )


def reverse_migrate_students(apps, schema_editor):
    """
    Reverse the migration by converting Student records back to User records
    """
    User = apps.get_model('accounts', 'User')
    Student = apps.get_model('accounts', 'Student')
    
    # Convert client users back to student type
    for student in Student.objects.all():
        client = student.client
        client.user_type = 'student'
        client.save()
        
        # Delete the student record
        student.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_sessions', '0005_alter_hours_table'),
        ('accounts', '0005_alter_user_user_type_student'),
    ]

    operations = [
        migrations.RunPython(
            migrate_students_to_new_model,
            reverse_migrate_students
        ),
    ]
