# Generated by Django 5.2.5 on 2025-09-07 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_user_type_student'),
        ('tutoring_sessions', '0006_auto_20250907_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_rates', to='accounts.student'),
        ),
    ]
