# Generated by Django 5.2.5 on 2025-09-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_sessions', '0008_refactor_charge_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', help_text='Payment status', max_length=20),
        ),
    ]
