# Generated by Django 5.2.5 on 2025-10-15 01:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tutoring_sessions", "0009_alter_charge_status"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Charge",
                ),
            ],
            # No database operations - table still needed by payments app
            database_operations=[],
        ),
    ]
