# Generated by Django 5.2.5 on 2025-10-23 05:16

from django.db import migrations, models


def set_payment_status_based_on_charges(apps, schema_editor):
    """Set payment_status based on whether session is part of a charge."""
    # Use raw SQL since the relationship might not be accessible in the migration state
    schema_editor.execute("""
        UPDATE tutoring_sessions
        SET payment_status = CASE
            WHEN EXISTS (
                SELECT 1
                FROM tutoring_sessions_charge_sessions
                WHERE tutoring_sessions_charge_sessions.hours_id = tutoring_sessions.id
            ) THEN 'paid'
            ELSE 'unpaid'
        END
    """)


class Migration(migrations.Migration):
    dependencies = [
        ("tutoring_sessions", "0010_move_charge_from_sessions"),
    ]

    operations = [
        migrations.AddField(
            model_name="hours",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("paid", "Paid by Student"),
                    ("tutor_paid", "Tutor Paid"),
                ],
                default="unpaid",
                help_text="Payment status of the session",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            set_payment_status_based_on_charges, reverse_code=migrations.RunPython.noop
        ),
    ]
