# Generated by Django 5.2.5 on 2025-12-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_sessions', '0013_add_rate_field_to_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='student_charged',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates if the student has been charged for this session.'),
        ),
        migrations.AlterField(
            model_name='hours',
            name='tutor_paid',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates if the tutor has been paid for this session.'),
        ),
    ]
