# Generated by Django 5.2.5 on 2025-10-15 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tutoring_sessions", "0010_move_charge_from_sessions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Charge",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "stripe_checkout_id",
                            models.CharField(
                                blank=True,
                                help_text="Stripe checkout session ID",
                                max_length=255,
                                null=True,
                                unique=True,
                            ),
                        ),
                        (
                            "amount",
                            models.DecimalField(
                                decimal_places=2,
                                help_text="Total sessions amount before credits",
                                max_digits=8,
                            ),
                        ),
                        (
                            "credits_applied",
                            models.DecimalField(
                                decimal_places=2,
                                default=0,
                                help_text="Credits applied to reduce the charge",
                                max_digits=8,
                            ),
                        ),
                        (
                            "final_amount",
                            models.DecimalField(
                                decimal_places=2,
                                help_text="Final amount after credits (amount - credits_applied)",
                                max_digits=8,
                            ),
                        ),
                        (
                            "currency",
                            models.CharField(
                                default="usd",
                                help_text="Currency code (e.g., 'usd')",
                                max_length=10,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "status",
                            models.CharField(
                                choices=[("pending", "Pending"), ("paid", "Paid")],
                                default="pending",
                                help_text="Payment status",
                                max_length=20,
                            ),
                        ),
                        (
                            "sessions",
                            models.ManyToManyField(
                                help_text="Sessions included in this charge",
                                related_name="charges",
                                to="tutoring_sessions.hours",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                help_text="The user (client) being charged",
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Charge",
                        "verbose_name_plural": "Charges",
                        "db_table": "tutoring_sessions_charge",
                        "ordering": ["-created_at"],
                    },
                ),
            ],
            # No database operations - table already exists as tutoring_sessions_charge
            database_operations=[],
        ),
    ]
