# Generated by Django 5.2.5 on 2025-08-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subjects_taught',
            field=models.TextField(blank=True, help_text="Comma-separated list of subjects this tutor can teach (e.g., 'Math, Physics, Chemistry')"),
        ),
    ]
