# Generated by Django 5.2.5 on 2025-09-07 04:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('tutor', 'Tutor'), ('admin', 'Admin')], max_length=10),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, help_text='Optional email for the student', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Optional phone number for the student', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('grade_level', models.CharField(blank=True, help_text="Current grade level (e.g., '9th Grade', 'Sophomore', 'K-12')", max_length=20)),
                ('subjects_studying', models.TextField(blank=True, help_text='Comma-separated list of subjects this student is studying')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the student (learning preferences, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='The client account this student belongs to', limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('client', 'first_name', 'last_name')},
            },
        ),
    ]
