# Generated by Django 5.2.5 on 2025-12-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_stripe_customer_and_billing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='billing_status',
            field=models.CharField(choices=[('missing', 'Missing'), ('invalid', 'Invalid'), ('valid', 'Valid')], default='missing', help_text='Current billing profile status for the user.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer identifier used for billing portal access.', max_length=255, null=True),
        ),
    ]
