# Generated by Django 5.2.5 on 2025-12-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_billing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='billing_status',
            field=models.CharField(choices=[('missing', 'Missing'), ('invalid', 'Invalid'), ('valid', 'Valid')], db_index=True, default='missing', help_text='Current billing profile status for the user.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer identifier used for billing portal access.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('tutor', 'Tutor'), ('admin', 'Admin')], db_index=True, max_length=10),
        ),
    ]
