# Generated by Django 5.2.5 on 2025-12-05 20:41

from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def set_last_session_at(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Hours = apps.get_model('tutoring_sessions', 'Hours')

    latest_client_session = (
        Hours.objects.filter(student__client=OuterRef("pk"))
        .order_by("-start_time")
        .values("start_time")[:1]
    )
    latest_tutor_session = (
        Hours.objects.filter(tutor=OuterRef("pk"))
        .order_by("-start_time")
        .values("start_time")[:1]
    )

    User.objects.filter(user_type="client").update(
        last_session_at=Subquery(latest_client_session)
    )
    User.objects.filter(user_type="tutor").update(
        last_session_at=Subquery(latest_tutor_session)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_billing_status_and_more'),
        ('tutoring_sessions', '0014_alter_hours_student_charged_alter_hours_tutor_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_session_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Timestamp of the user's last tutoring session.", null=True),
        ),
        migrations.RunPython(set_last_session_at, migrations.RunPython.noop),
    ]
